server:
  port: 8082

spring:
  application:
    name: booking-service

  retry:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      hotel-service:
        connectTimeout: 3000
        readTimeout: 3000
        retryer: spring-retry

jwt:
  secret: "my-super-secure-jwt-key-with-32-chars-1234567890"

internal:
  key: "super-internal-key-777"

hotel:
  service:
    url: http://localhost:8083
logging:
  level:
    org.springframework.security: DEBUG
    com.example.bookingservice: DEBUG